spring:
   application:
      name: discovery
eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://{eureka.instance.hostname}:${server.port}/eureka/
#   cloud:
#      loadbalancer:
#         ribbon:
#            enabled: false
server:
   port: 8761
