spring:
   application:
      name: event-service
   datasource:
      url: jdbc:postgresql://localhost:5433/event_db
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
eureka:
   instance:
#      prefer-ip-address: true
#      ip-address: 192.168.2.16${server.port}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#         defaultZone: http://localhost:8761/eureka
server:
   port: 8084
