spring:
   application:
      name: event-service
   datasource:
      url: jdbc:postgresql://localhost:5433/event_db
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
server:
   port: 8084
