spring:
   datasource:
      url: jdbc:postgresql://localhost:5433/event_db
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
server:
   port: 8080

eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         default-zone:  http://eureka-server-2:8762/eureka/,http://eureka-server-1:8761/eureka/,http://eureka-server-3:8763/eureka
