server:
   port: 8080

spring:
   application:
      name: gateway
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
      gateway:
         discovery:
            locator:
               enabled: true
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka