server:
   port: 8080

spring:
   application:
      name: gateway
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
      gateway:
         routes:
            filters:
               - name: AddRequestHeader
                 args:
                    name: X-Simple-Header
                    value: simple
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true
eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka