spring:
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
      gateway:
         routes:
            - id: event-route
              uri: http://localhost:8084
              predicates:
                 - Path=/events/**
            -  id: registration-route
               uri: http://localhost:8081
               predicates:
                  - Path=/registration/**

server:
   port: 8080

eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         default-zone:  http://eureka-server-2:8762/eureka/,http://eureka-server-1:8761/eureka/,http://eureka-server-3:8763/eureka
