spring:
   application:
      name: registration-service
   datasource:
      url: jdbc:postgresql://localhost:5433/registration_db
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   cloud:
      loadbalancer:
         ribbon:
            enabled: false

server:
   port: 8081

eureka:
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone:  http://localhost:8762/eureka/,http://localhost:8761/eureka/,http://localhost:8763/eureka
